mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: "127.0.0.1:9090"
dns:
  enable: true
  ipv6: false
  default-nameserver: null
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver: null
  fallback: ["https://doh.dns.sb/dns-query", "https://dns.cloudflare.com/dns-query", "https://dns.twnic.tw/dns-query", "tls://8.8.4.4:853"]
  fallback-filter: {geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32]}
proxies: [{alterId: 0, cipher: auto, flow: "", name: ğŸ’dl.ops.kgvn.garenanow.com, network: ws, port: 80, server: 14.225.207.9, type: vmess, uuid: 06ccbfab-4011-4bd6-9e49-74d15e4b9c45, ws-opts: {headers: {Host: dl.ops.kgvn.garenanow.com}, path: /}}, {alterId: 0, cipher: "auto", flow: "", name: ğŸš€dl.ops.kgvn.garenanow.com, network: ws, port: 80, server: 14.225.207.9, type: vmess, uuid: 59aa5e48-b0d6-438b-a51f-63f2fa2f1594, ws-opts: {headers: {Host: dl.ops.kgvn.garenanow.com}, path: /}}, {alterId: 0, cipher: auto, flow: "", name: ğŸš€mydio.vn, network: ws, port: 80, server: xgame.anhtai4g.me, type: vmess, uuid: 4f0ffe99-d787-46a2-93da-11c5d50d439d, ws-opts: {headers: {host: mydio.vn}, path: /xgame.anhtai4g.me}}]
proxy-groups:
  - {name: NhutGG, type: select, proxies: [DIRECT, ğ€ğ”ğ“ğ ğ’ğ„ğ‹ğ„ğ‚ğ“], hidden: null, icon: "https://raw.githubusercontent.com/nhutggvnvn/nhutgg.github.io/main/img/iconstash.png", ssid-policy: {cellular: ğ€ğ”ğ“ğ ğ’ğ„ğ‹ğ„ğ‚ğ“, default: DIRECT, wifi: direct}, interval: 10, lazy: true}
  - icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    interval: 7200
    name: Auto Change
    proxies:
      - ğ’ğ„ğ•ğ„ğ‘ All SUB
      - ğ€ğ”ğ“ğ ğ’ğ„ğ‹ğ„ğ‚ğ“
      - ğŸ’dl.ops.kgvn.garenanow.com
      - ğŸš€dl.ops.kgvn.garenanow.com
      - ğŸš€mydio.vn
    type: fallback
    use:
      - PANEL
  - {name: ğ€ğ”ğ“ğ ğ’ğ„ğ‹ğ„ğ‚ğ“, type: select, proxies: [ğ’ğ„ğ•ğ„ğ‘ All SUB, ğŸ’dl.ops.kgvn.garenanow.com, ğŸš€dl.ops.kgvn.garenanow.com, ğŸš€mydio.vn], use: [PANEL, VPNSub], include-all: null, use-url: null, icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Round_Robin.png", interval: 10, lazy: true}
  - icon: https://raw.githubusercontent.com/Orz-3/mini/master/Alpha/Team.png
    name: ğ’ğ„ğ•ğ„ğ‘ All SUB
    type: select
    use:
      - PANEL
      - CUSTUM
      - VPNSub
    interval: 10
    lazy: true
    proxies:
      - ğŸš€dl.ops.kgvn.garenanow.com
      - ğŸ’dl.ops.kgvn.garenanow.com
      - ğŸš€mydio.vn
  - {name: Sever LQ, type: url-test, proxies: [ğŸ’dl.ops.kgvn.garenanow.com, ğŸš€dl.ops.kgvn.garenanow.com], use: null, include-all: null, use-url: null, icon: "https://raw.githubusercontent.com/nhutggvnvn/Qure/master/gg/lienquanicon.png", interval: 10, lazy: true}
  - {name: Sever Viet Nam, type: url-test, proxies: null, url: "http://www.gstatic.com/generate_204", interval: 10, hidden: null, use-url: null, icon: "https://cdn1.iconfinder.com/data/icons/ensign-11/512/280_Ensign_Flag_Nation_vietnam-1024.png", use: [PANEL,CUSTUM,VPNSub], filter: "ğŸ‡»ğŸ‡³", lazy: true}
  - name: Sever Singapore
    type: url-test
    icon: https://raw.githubusercontent.com/huynt79/0bik/main/IMG_0800.png
    use:
      - PANEL
      - CUSTUM
      - VPNSub
    filter: (ğŸ‡¸ğŸ‡¬) 
  - name: Sever Japan
    type: url-test
    icon: https://raw.githubusercontent.com/huynt79/0bik/main/IMG_0801.png
    use:
      - PANEL
      - CUSTUM
      - VPNSub
    filter: (ğŸ‡¯ğŸ‡µ)
  - name: Sever USA
    type: url-test
    icon: https://raw.githubusercontent.com/huynt79/0bik/main/4E247D5D-7C20-4F8F-8D2C-D40852FCE54C.png
    use:
      - PANEL
      - CUSTUM
      - VPNSub
    filter: (ğŸ‡ºğŸ‡¸)
  - name: Reject
    #  - {name: ğ€ğ”ğ“ğ ğ€ğ‹ğ‹, type: url-test, proxies: null, url: 'http://www.gstatic.com/generate_204', interval: 10, hidden: null, use-url: null, icon: 'https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png', use: [VPN], filter: null, lazy: true}

    proxies:
      - DIRECT
      - REJECT
    type: select
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/Adblock.png
    lazy: true
rules:
  - DOMAIN-SUFFIX,ocsp-lb.apple.com.akadns.net,REJECT
  - DOMAIN-SUFFIX,ocsp-a.g.aaplimg.com,REJECT
  - DOMAIN-SUFFIX,ocsp-us-lb.apple.com.akadns.net,REJECT
  - DOMAIN-SUFFIX,ocsp2-lb.apple.com.akadns.net,REJECT
  - DOMAIN-SUFFIX,ocsp2.g.aaplimg.com,REJECT
  - DOMAIN-SUFFIX,axm-app.apple.com,REJECT
  - DOMAIN-SUFFIX,comm-cohort.ess.apple.com,REJECT
  - DOMAIN-SUFFIX,comm-main.ess.apple.com,REJECT
  - DOMAIN-SUFFIX,gdmf.apple.com,REJECT
  - DOMAIN-SUFFIX,mesu.apple.com,REJECT
  - DOMAIN-SUFFIX,ocsp2.apple.com,REJECT
  - DOMAIN-SUFFIX,ocsp.apple.com,REJECT
  - DST-PORT,5223,ğ€ğ”ğ“ğ ğ’ğ„ğ‹ğ„ğ‚ğ“
  - DOMAIN-SUFFIX,*.apple.com,ğ€ğ”ğ“ğ ğ’ğ„ğ‹ğ„ğ‚ğ“
  - RULE-SET,AllSERVERADS,Reject
  - RULE-SET,HostVN,Reject
  - DOMAIN,app-measurement.com,REJECT
  - MATCH,NhutGG
rule-providers: {HostVN: {behavior: domain, format: yaml, interval: 0, url: "https://raw.githubusercontent.com/bigdargon/hostsVN/master/option/hostsVN-clash-rule.yaml"}, AllSERVERADS: {behavior: domain, format: yaml, interval: 0, url: "https://raw.githubusercontent.com/lonely0811/olsd/main/stash/AllSERVERADS.yaml"}}
http:
  mitm:
    - "-redirector*.googlevideo.com"
    - "*.googlevideo.com"
    - "www.youtube.com"
    - "s.youtube.com"
    - "youtubei.googleapis.com"
    - "mobile-api.adguard.org"
  script:
  #- match: ^https?:\/\/mobile-api\.adguard\.org\/api\/.+\/ios_validate_receipt
  #name: ads
  #type: response
  #require-body: true
  #timeout: 10
  rewrite:
  #- (^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302
script-providers:
#ads:
#url: https://github.com/lonely0811/olsd/raw/main/ad.js
#interval: 86400
proxy-providers:
  PANEL:
    interval: 0
    url: https://nhutggvn.online:8889/sub/nhutggvn1
  CUSTUM:
    interval: 0
    url: https://anhtai4g.me/api/v1/client/subscribe?token=1ce69a2e5f36caa8047d157064c955ee
  VPNSub:
    interval: 0
    url: https://4gsieuviet.com/api/v1/client/subscribe?token=fc58397f4dc194bf462837945b5e7547
lyingBird:
  interval: 3600
  url: "https://config.nhutgg.io.vn/download.php"
